### ISSUE TITLE
Sandbox doesn't work

### ISSUE THREAD

**Issue by hakankaraduman** [kettanaito/atomic-layout-docs#8]
When I look at the getting started section's first sandbox, it doesn't work.

I see the main index.js is nested, not at the root, and couldn't find how it can be changed. It would be a lot nice to make it work for us users without changing or working on the examples.

**Comment by kettanaito** [comment]
Hey, @hakankaraduman. Thanks for raising this. I'll take a look and make sure that sandbox is functional. Will update here.

**Comment by kettanaito** [comment]
There has been apparently some changes in the embed settings. I've changed the link, so now you should be able to see the working sandbox on the [First Composition](https://redd.gitbook.io/atomic-layout/getting-started/first-composition) page.

**Comment by hakankaraduman** [comment]
Hi again and thanks for the update. This is probably my lack of knowledge now.

I see the example embeded on the page, but when I click the open sandbox, the html on the right shows empty. I coudln't understand how to open it on the right and play with the code. Does it need to be separate sandboxes for first composition and responsive composition maybe? To make it easier for people to understand. This way it wouldn't require knowledge on how sandbox works.

**Comment by kettanaito** [comment]
Hey, @hakankaraduman, no worries!

That's not your lack of knowledge, that's my confusing example setup. It's broken down into steps, so in order to see the first step:

1. Open the `src/steps-first-composition/index.js`.
1. Click on "Module view" in the preview panel on the right (next to the address bar).

Here's a screenshot with those actions:

<img width="1652" alt="Screen Shot 2020-06-01 at 08 54 50" src="https://user-images.githubusercontent.com/14984911/83383617-cd92a700-a3e5-11ea-96fe-486bd62d43f4.png">

Please let me know if that helps!
